<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration "baseline" volontairement vide.
 *
 * `doctrine:migrations:diff` a généré ici un diff purement cosmétique
 * entre le style de schéma que Doctrine produirait spontanément et le
 * schéma réel (créé par 001_mpd.sql, source de vérité validée au
 * Jalon 3) : SERIAL -> GENERATED BY DEFAULT AS IDENTITY, ENUM natif ->
 * VARCHAR(255), renommage des contraintes/index générés par Doctrine.
 *
 * Le diff contenait aussi `DROP INDEX idx_exemplaire_position` : Doctrine
 * ne connaît pas cet index GiST (il n'est déclaré nulle part dans le
 * mapping ORM, seulement dans 001_mpd.sql) et le traite comme orphelin.
 * L'appliquer aurait supprimé l'index utilisé par la recherche de
 * proximité (F4, ST_DWithin) — non négociable, jamais fait. Idem pour le
 * trigger trg_maj_position_exemplaire, hors du contrôle de l'ORM.
 *
 * Cette migration est donc un no-op assumé, marqué comme exécuté (voir
 * `doctrine:migrations:version --add`) sans qu'aucun up()/down() ne
 * tourne : elle sert de point de départ (baseline) à la table des
 * migrations Doctrine, sans toucher au schéma existant. Les migrations
 * suivantes ne diffèreront plus que sur de vrais changements de schéma.
 */
final class Version20260824102256 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline (no-op) — le schéma est possédé par 001_mpd.sql, pas par doctrine:schema:update.';
    }

    public function up(Schema $schema): void
    {
        // Volontairement vide — voir la docblock de la classe.
    }

    public function down(Schema $schema): void
    {
        // Volontairement vide — voir la docblock de la classe.
    }
}
